Update file-check.yaml

diff --git a/.github/workflows/file-check.yaml b/.github/workflows/file-check.yaml
--- a/.github/workflows/file-check.yaml
+++ b/.github/workflows/file-check.yaml
@@ -45,6 +45,8 @@ jobs:
           if [[ "$MISSING_FILE" == "true" ]]; then
             echo "- ❌ **test4/test4-test.sh** is missing" >> $GITHUB_STEP_SUMMARY
             echo "- 🏷️ Added label: \`missing-required-file\`" >> $GITHUB_STEP_SUMMARY
+            echo "❌ Failing the workflow because the required file is missing."
+            exit 1
           else
             echo "- ✅ File is present." >> $GITHUB_STEP_SUMMARY
           fi
